### ISSUE TITLE
FetchEncodedBitmapImageAsync crashes app when URI returns a 204

### ISSUE THREAD

**Issue by rigdern** [phongcao/image-pipeline-windows#12]
I put the following code into an event handler to repro this bug:

```c#
private async void Button_Tapped(object sender, TappedRoutedEventArgs e)
{
    try
    {
        var uri = new Uri("https://avatar.skype.com/v1/avatars/live:adam.comella/public?returnDefaultImage=false");
        var imagePipeline = ImagePipelineFactory.Instance.GetImagePipeline();
        Debug.WriteLine("UI fetching image...");
        var bitmap = await imagePipeline.FetchEncodedBitmapImageAsync(uri);
        Debug.WriteLine("UI image fetched!");
    }
    catch
    {
        Debug.WriteLine("UI image fetching failed due to exception");
    }
}
```

The result is that this exception is thrown:

```
The component cannot be found. (Exception from HRESULT: 0x88982F50) 
```

An interesting thing about that image's URI is that it returns an HTTP status code of `204 No Content` rather than `200 OK`.

An interesting thing about the exception is that it results in the app crashing even though the call to `FetchEncodedBitmapImageAsync` is wrapped in a `try/catch`. Do you know why that is?

This bug is causing my react-native-windows application to crash.

Adam Comella
Microsoft Corp.

**Comment by phongcao** [comment]
I guess that the exception is thrown on the UI thread so that try/catch block couldn't catch:
```C#    
    await DispatcherHelpers.RunOnDispatcherAsync(async () =>
    {
        using (var outStream = new InMemoryRandomAccessStream())
        using (var writeStream = outStream.AsStreamForWrite())
        {
            await writeStream.WriteAsync(bytesArray, 0, supportedSize);
            outStream.Seek(0);
            BitmapImage bitmapImage = new BitmapImage();
            await bitmapImage.SetSourceAsync(outStream).AsTask().ConfigureAwait(false);
            taskCompletionSource.SetResult(bitmapImage);
        }
    })
    .ConfigureAwait(false);
```
The error occurs because it tries to set invalid stream source to BitmapImage. If I re-position the try/catch block (move it inside the dispatcher, the app won't crash). However, I think that the error should be better handled in the network module. I'm on a biz trip now so will look into this on the weekend.
