### ISSUE TITLE
FetchEncodedBitmapImageAsync throws exception in UI thread when image is invalid

### ISSUE THREAD

**Issue by btpnlsl** [phongcao/image-pipeline-windows#15]
This is very similar to #12 

I am trying to fetch an image using the following sample code:

```
private async void Button_Tapped(object sender, TappedRoutedEventArgs e)
{
    try
    {
        var uri = new Uri("https://avatar.skype.com/v1/avatars/pejacepoha?auth_key=-1104745216&cacheHeaders=true&returnDefaultImage=false&size=m");
        var imagePipeline = ImagePipelineFactory.Instance.GetImagePipeline();
        Debug.WriteLine("UI fetching image...");
        var bitmap = await imagePipeline.FetchEncodedBitmapImageAsync(uri);
        Debug.WriteLine("UI image fetched!");
    }
    catch
    {
        Debug.WriteLine("UI image fetching failed due to exception");
    }
}
```

As far as I can tell I am receiving a 200 OK code from the HTTPS request, but the image data is incorrect and has a content length of 1.  Here is from Fiddler:

HTTP/1.1 200 OK
Cache-Control: max-age=604800
Content-Length: 1
Content-Type: image/jpeg; ver=1.0
Expires: Fri, 19 Jan 2018 21:23:48 GMT
Server: Microsoft-HTTPAPI/2.0
X-Avatar-Type: custom
X-Avatar-Size: s
X-Content-Type-Options: nosniff
X-Skype-Request-Id: cf84fb6b
X-Skype-Processing-Time: 59.91510
Date: Fri, 12 Jan 2018 21:23:48 GMT

I modified the Example code and I can see the exception is happening from this line in ImagePipelineCore.cs:

`                                    await bitmapImage.SetSourceAsync(outStream).AsTask().ConfigureAwait(false);
`

**Comment by btpnlsl** [comment]
It looks like that block of code is the only code within a RunOnDispatcherAsync block that doesn't try/catch.

**Comment by phongcao** [comment]
@btpnlsl Could you please help verify?

**Comment by btpnlsl** [comment]
@phongcao looks good.  the exception is passed up to the caller.
