### ISSUE TITLE
dataSource.Subscribe() fails for GIF based dataSource

### ISSUE THREAD

**Issue by mrousal** [phongcao/image-pipeline-windows#21]
var request = ImageRequestBuilder.NewBuilderWithSource(uri).Build();
var dataSource = imagePipeline.FetchDecodedImage(request, null);
...
dataSource.Subscribe(dataSubscriber, FBCore.Concurrency.CallerThreadExecutor.Instance);

fails with:

{System.NotImplementedException: The method or operation is not implemented.   at ImagePipeline.Decoder.ImageDecoder.DecodeGifAsync(EncodedImage encodedImage, ImageDecodeOptions options)
   at ImagePipeline.Producers.DecodeProducer.ProgressiveDecoder.<DoDecode>d__13.MoveNext()}

for local GIF files (for example the one attached)

![sending](https://user-images.githubusercontent.com/4840550/40722485-c06027f2-641c-11e8-9758-7badda5d5303.gif)

**Comment by phongcao** [comment]
I'm going to implement GIF decoder (with [forceStaticImage](http://frescolib.org/javadoc/reference/com/facebook/imagepipeline/common/ImageDecodeOptions.html#forceStaticImage) option) in the next version and it should fix this issue.
